### ISSUE TITLE
New Topic Streams for EPAM/OMS project development

### ISSUE THREAD

**Issue by plweller3** [clingen-data-model/kafka-pipe-service#2]
Please create two new topic streams for the EPAM/OMS projects.

The names of the streams can be expert-panel-source-web and expert-panel-source-epam.

It has been a while since I've touched Kafka so I don't really recall everything you need.  There will be several systems that will be sending and receiving data from this topic streams.  Two will be in the B/G Google Cloud.  Probably two in UNC's deployment area.  And some local development platforms.  Please advise and direct on best way to handle any authentication.  Also please point to any instructions/directions on sending and receiving from them.

We don't need the streams today, but will likely be ready for them sometime mid-April.

**Comment by theferrit32** [comment]
@plweller3 I can create these topics now. For authentication we use confluent service accounts and API keys, and assign consumer groups and topics that the service account can read and/or write to. The UNC team has a key already so I will just add them to these topics.

I can create a service account and key for the B/G project as well. Kafka supports prefixed consumer groups so if I create one like `bg_prod` then anything that starts with that string will work (bg_prod, bg_prod_test, bg_prod_1, etc) and you can use this to have different topic offsets for different applications or environments.

We have a dev, stage, and prod kafka cluster and the API keys are local to a cluster. If you want to be able to run through some test runs first I can create these in the `stage` cluster.

**Comment by larrybabb** [comment]
@plweller3 please communicate and respond to updates here so that we know when you are satisfied that the original request is complete. If a new request spawns out of the conversation, please create a new ticket and we will link them. Thanks.

**Comment by larrybabb** [comment]
@theferrit32 Would you quickly confirm the consumer group naming with @tnavatar? It would be good to know that we have some method to our madness for naming consumer groups. If it is inconsequential then the name is fine (or we should simply allow the requester to name their group). If I am overstepping due to ignorance please let me know.

**Comment by plweller3** [comment]
If I follow correctly, this would be auth credentials, correct?  

I could use whatever you set up for the new topics, but only I could use them on those topics else pointers would change, correct?  Or is there an individual component also?

That would be fine.  Setting up in the stage cluster would also be fine as we work the actual message details.

Thanks!

**Comment by theferrit32** [comment]
@plweller3 the api key grants access to a topic(s) and consumer group(s) within a kafka cluster. Each consumer group is basically a set of file offsets into a set of topics and any number of topics and consumer groups can be added to an api key, even after creation, so you wouldn't need to update your configuration if the topics assigned to it need to change later. 

@larrybabb The name doesn't really matter but it's nice for it to kind of be related to who or what application is using it. We are using prefix-based consumer groups because it lets clients create as many consumer groups as they want on their own, while still helping prevent accidental collision between developers/teams.
